### ISSUE TITLE
Add MSID metric

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/photosynthesis.metrics#16]
**Is your feature request related to a problem? Please describe.**
This metric showed to be comparable in quality of predictions with FID and KID scores.

**Describe the solution you'd like**
Take code from this repo https://github.com/xgfs/msid/tree/master/msid and potentially refactor it to make all FID, KID, MSID metrics interface look a like.

**Comment by snk4tr** [comment]
Implemented in #20
