### ISSUE TITLE
Metric: Visual Information Fidelity (VIF)

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/photosynthesis.metrics#33]
**Is your feature request related to a problem? Please describe.**
Need to add image-to-image metric used in [this challenge](https://sites.google.com/view/calgary-campinas-dataset/home/mr-reconstruction-challenge).

**Describe the solution you'd like**
Fit existing implementation or create a custom one

**Comment by zakajd** [comment]
Closed by #47
