### ISSUE TITLE
Slow InceptionV3 initialisation

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/photosynthesis.metrics#44]
**Describe the bug**
Model init for InceptionV3 model both from this repo and from `torchvision.models` take very long time. Usually ~180-200 seconds, while other models init in 2-3 sec. 
Problem arose a couple of month ago and discussed [here](https://discuss.pytorch.org/t/torchvisions-inception-v3-takes-much-longer-to-load-than-other-models/68756)

**To Reproduce**
```python
from torchvision.models import inception_v3  
import photosynthesis_metrics as pm
import scipy
print(scipy.__version__)

model = inception_v3(pretrained=True, transform_input=True, progress=True)
pm_model = pm.feature_extractors.fid_inception.InceptionV3(
    resize_input=True, 
    normalize_input=True,
    requires_grad=False,
    use_fid_inception=True,
)
```

This could should take around 6 minutes to complete (3 minutes per model).

**Expected behaviour**
Fast model initialisation, not longer than a couple of seconds.

**Fix**
Problem comes from `scipy` package with version *1.4.1* defined in requirements.txt.
Uninstalling newer version and installing 1.3.3 fixed the issue for me. The loading time is much faster now. Just had to do `pip install --upgrade scipy==1.3.3`

**Proposed solution**
Change version in requirements.txt 
This will increase testing speed **10x** (now all tests run in 10 minutes, because of 3 model inits, after fix they will run in 1 minute).

**Comment by snk4tr** [comment]
Closed in #45
