### ISSUE TITLE
Pull request templates

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/photosynthesis.metrics#52]
**Is your feature request related to a problem? Please describe.**
Now PRs are unstructured, which makes ideas behind them less clear and harder to understand.

**Describe the solution you'd like**
Adjust one of the common templates to meet the needs of our project.

**Comment by denproc** [comment]
The PR template seems to be not triggered by GitHub when a PR is created. There is no info in [project settings](https://github.com/photosynthesis-team/photosynthesis.metrics/community).

According to [help](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository), the default template should be stored at `.github/pull_request_template.md`. 
In case of multiple PR templates with *query* parameters, the folder `PULL_REQUEST_TEMPLATE` should be used for storing the templates. [Source](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters).

**Proposal**
Move existing PR template to `.github` folder.
