### ISSUE TITLE
Strange TV loss

### ISSUE THREAD

**Issue by smikhai1** [photosynthesis-team/photosynthesis.metrics#57]
What is the purpose of defining the TV loss as the absolute difference between the Total Variations of predicted tensor and the target one? Usually, TV used as a regularizer applied only to the predicted tensor.

I can make a pull request with the correction.

**Comment by zakajd** [comment]
Hi!
Yes, it's a good point. I made TVLoss to be compatible with other full-reference methods, that's why it takes 2 inputs.  But a fast google search showed, that it's not common to use it this way. 

So you are welcome to change it. Please also change the README file description  and tests

**Comment by smikhai1** [comment]
Nice, got it!

**Comment by denproc** [comment]
Closed with #58
