### ISSUE TITLE
BRISQUE returns nan

### ISSUE THREAD

**Issue by PavelOstyakov** [photosynthesis-team/photosynthesis.metrics#86]
Hi, I've found that if a tensor contains all (or almost all) zeros, brisque returns nan. Is this behavior expected?

```
In [1]: from photosynthesis_metrics import brisque

In [2]: import torch

In [3]: prediction = torch.zeros(3, 3, 256, 256)

In [4]: brisque(prediction)
Out[4]: tensor(nan)

In [5]: prediction[:, :, 0, 0] = 1

In [6]: brisque(prediction)
Out[6]: tensor(nan)
```

**Comment by snk4tr** [comment]
Summon @denproc

**Comment by denproc** [comment]
Hey guys,
Yep, that's a bug, which related to the range of values in tensor. In this setting `torch.ones(1,1,256,256)` also leads to `nan`.
 The `nan` value comes from `_aggd_parameters`. The bug fix is coming.
